travis:
  secure:
    BINSTAR_TOKEN: gExHWy8AwuSiUX6042V5Jr/F6aa+XjHt1+zoj5o2Aw0uwkdEOv3wM6mcWgy+Cl5rNzQSIO2M/rvkCWft8hJlH4t12lC92in05eM0nv6qp143c5ZspXcukO4ZvVYKp+hpEyvtK1x6YT9miA4oNTZ+oAl4nUpA8CddRQ68kZFhZHmsqAIX2hfB6PamvS94+8cfjQ1/IfDMNLBduVyc2AXXwiGdwqJoGWkKmhqIEWH9z7Ge6j6Icb6sBz2lKqKW9L/0R17uC/JJVUecAnRKXGQFH/mHEZJIXmV6iPb7Ez5kupypY9UoziEGh2UcGlvxBIrEaycmfq1XMAFVGfp/GQx19CWgMTjs0SFCb1k3MqUrY6/T3EkitcxhKMP8fYvxgwYFjii4QjNOXfI8+NAHeQRqXKNDdXQ8YtcN8TjjwthfiHG2L/WwVXsYYdEZdBVxxkDTGsqoF5nrKvC8SybM+fRxRkiWdtZ3SU4AG0TIChgGXEaA5UZEQYRfceDiO34mw9rw86VQqoLY828h6LXv9I+aUQkq2DKjzAuIMRtgvJfDKfftfKKXeXT55VnsvaCxcOLkUhKGrV05agNzLAjyIdgpzw9cXBcoEJgpMtYo99kOL3FWC0v1RNjOBUPRiCJYDrH42g3BkSRr9AkkDLqXpGo0eWMaGCqPthXK47rXiZyseaw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
